### ISSUE TITLE
Modify shell startup files PBA fails when agent is run from docker container

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1055]
## Describe the bug

When the user runs the monkey agent from the island (docker container) the `result` field of the `Modify shell startup files` PBA is empty, resulting in an exception being thrown.

```
2021-03-25 19:00:59,776 [18:139916855985920:DEBUG] base_telem._log_telem_sending.57: Telemetry contents: {"command": "", "result": [], "name": "Modify shell startup file", "hostname": "starbuck", "ip": "127.0.1.1"}

...

2021-03-25 19:00:59,815 - processing.py:37 - process_telemetry() - ERROR - Exception caught while processing telemetry. Info: list index out of range
Traceback (most recent call last):
  File "/monkey/monkey_island/cc/services/telemetry/processing/processing.py", line 33, in process_telemetry
    TELEMETRY_CATEGORY_TO_PROCESSING_FUNC[telem_category](telemetry_json)
  File "/monkey/monkey_island/cc/services/telemetry/processing/post_breach.py", line 47, in process_post_breach_telemetry
    telemetry_json['data'] = convert_telem_data_to_list(telemetry_json['data'])
  File "/monkey/monkey_island/cc/services/telemetry/processing/post_breach.py", line 26, in convert_telem_data_to_list
    if type(data['result'][0]) is list:  # multiple results in one pba
IndexError: list index out of range
```

This issue appears to be somewhat intermittent.

## To Reproduce
1. Install Infection Monkey docker container
2. In the configuration, enable the `Modify shell startup files` PBA.
3. Run infection monkey from the island

## Expected behavior
The logic in `monkey/monkey_island/cc/services/telemetry/processing/post_breach.py` should be improved so that an error is not thrown. More importantly, it should be determined why this PBA fails inside a docker container.

## Machine version (please complete the following information):
 - OS:  Linux

**Comment by mssalvatore** [comment]
Duplicate of #1507
