### ISSUE TITLE
AppImage not using isolated python environment?

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1176]
# Spike

I've been getting this error on Ubuntu 18.04, when running AppImage:
```
2021-05-18T08:07:29.937+0000 I  SHARDING [LogicalSessionCacheReap] Marking collection config.transactions as collection version: <unsharded>
2021-05-18T08:07:30.016+0000 I  FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
2021-05-18T08:07:30.037+0000 I  SHARDING [ftdc] Marking collection local.oplog.rs as collection version: <unsharded>
2021-05-18 08:07:32,177 - environment_singleton.py:47 - initialize_from_file() - INFO - Monkey's env is: PasswordEnvironment
Traceback (most recent call last):
  File "./monkey_island.py", line 33, in <module>
    from monkey_island.cc.main import main  # noqa: E402
  File "/tmp/.mount_InfectSlpkoS/usr/src/monkey_island/cc/main.py", line 22, in <module>
    from monkey_island.cc.app import init_app  # noqa: E402
  File "/tmp/.mount_InfectSlpkoS/usr/src/monkey_island/cc/app.py", line 11, in <module>
    from monkey_island.cc.resources.attack.attack_config import AttackConfiguration
  File "/tmp/.mount_InfectSlpkoS/usr/src/monkey_island/cc/resources/attack/attack_config.py", line 4, in <module>
    from monkey_island.cc.resources.auth.auth import jwt_required
  File "/tmp/.mount_InfectSlpkoS/usr/src/monkey_island/cc/resources/auth/auth.py", line 9, in <module>
    from jwt import PyJWTError
ImportError: cannot import name 'PyJWTError' from 'jwt' (/home/vakaris_zilius/.local/lib/python3.7/site-packages/jwt/__init__.py)
```

I've fixed the error by doing `pip3 uninstall PyJWT`.

This shows that the way AppImage uses python somehow clashes with the python env present on the system. I have not been able to reproduce the error later, by installing PyJWT. 

## Objective
Try to reproduce the bug, maybe by installing a very outdated PyJWT? AppImage should have a self-contained python with packages as far as I understand. That python shouldn't be overridden by systems python. Either way, it would be best to get to the bottom of this to assess whether or not this is a bug/problem worth fixing

## Scope
AppImage builder

**Comment by mssalvatore** [comment]
I would start by checking how the `PYTHONPATH` environment variable is set. You could add an `echo` to [appimage/AppRun](https://github.com/guardicore/monkey/blob/085a1334fac8215e3749bd1de0d631daa29ba85a/appimage/AppRun) to find out.

AppImages are just a [directory](https://docs.appimage.org/reference/appdir.html) stored as a squashfs. This enables you to quickly modify and iterate in order to debug.

1. Build an AppImage package using https://github.com/guardicore/monkey/blob/085a1334fac8215e3749bd1de0d631daa29ba85a/appimage/build_appimage.sh
2. [Extract the contents of the AppImage](https://github.com/guardicore/monkey/blob/085a1334fac8215e3749bd1de0d631daa29ba85a/appimage/build_appimage.sh) by running the AppImage package with the `--appimage-extract` option. This will create a new directory called `squashfs-root`
3. Make any changes you want to any files in `squashfs-root`
4. Build a new AppImage that includes your changes by running `ARCH=64 appimagetool squashfs-root`
