### ISSUE TITLE
in kali linux build error:IOError: [Errno 2] No such file or directory: './bin/sc_monkey_runner32.so'

### ISSUE THREAD

**Issue by hktalent** [guardicore/monkey#163]
in kali linux build error
```
cd monkey/infection_monkey
./build_linux.sh
..................
22331 INFO: Executing - strip /root/.cache/pyinstaller/bincache10_py27_64bit/libpython2.7.so.1.0
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 32, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/api.py", line 411, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/api.py", line 196, in __init__
    self.__postinit__()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/api.py", line 259, in assemble
    dist_nm=inm)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/utils.py", line 197, in checkCache
    digest = cacheDigest(fnm, redirects)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/utils.py", line 341, in cacheDigest
    data = open(fnm, "rb").read()
IOError: [Errno 2] No such file or directory: './bin/sc_monkey_runner32.so'
```

**Comment by itaymmguardicore** [comment]
It appears like you're missing the sambacry binaries. You need to build those first, before you can build the monkey itself.

There are detailed build instructions in the readme.txt file under the infection_monkey folder (here: https://github.com/guardicore/monkey/blob/master/infection_monkey/readme.txt).

Hope that helps.
