### ISSUE TITLE
Security Hub findings' export fails

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#1704]
## Describe the bug
Security Hub findings aren't exported on AWS and fail with the following error (found on `agent-refactor`).
```
2022-02-08 17:55:05,980 - aws_exporter.py:155 - _send_findings() - ERROR - AWS security hub findings failed to send. Error: Parameter validation failed:
Invalid length for parameter Findings, value: 0, valid min length: 1
Traceback (most recent call last):
  File "/tmp/.mount_InfectZV3lBq/usr/src/monkey_island/cc/services/reporting/aws_exporter.py", line 141, in _send_findings
    import_response = security_hub_client.batch_import_findings(Findings=findings_list)
  File "/tmp/.mount_InfectZV3lBq/opt/python3.7/lib/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/tmp/.mount_InfectZV3lBq/opt/python3.7/lib/python3.7/site-packages/botocore/client.py", line 678, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/tmp/.mount_InfectZV3lBq/opt/python3.7/lib/python3.7/site-packages/botocore/client.py", line 726, in _convert_to_request_dict
    api_params, operation_model)
  File "/tmp/.mount_InfectZV3lBq/opt/python3.7/lib/python3.7/site-packages/botocore/validate.py", line 337, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter Findings, value: 0, valid min length: 1
2022-02-08 17:55:05,982 - aws_exporter.py:52 - handle_report() - ERROR - Exporting findings to aws failed
```

## To Reproduce
1. Run Monkey on AWS (refer to [this](https://www.guardicore.com/infectionmonkey/docs/usage/integrations/aws-security-hub/) and the AWS testing guide on Confluence, if needed).
2. See error in Island logs.

## Expected behavior
Security Hub findings should be exported successfully.

## Machine version (please complete the following information):
 - OS: Linux

**Comment by ilija-lazoroski** [comment]
Resolved in #2443
