### ISSUE TITLE
Custom PBA on Windows throws a UnicodeDecodeError

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#2215]
## Describe the bug
Running a custom PBA on Windows (haven't tried on Linux) throws the following error:
```
2022-08-25 13:43:12,020 [35320:PBAThread:ERROR] automated_master._run_plugins.237: Got unhandled exception when running post-breach action plugin PluginConfiguration(name='CustomPBA', options={'linux_command': '', 'linux_filename': '', 'windows_command': 'a.bat & del a.bat', 'windows_filename': 'a.bat'}). Plugin was passed to <bound method AutomatedMaster._run_pba of <infection_monkey.master.automated_master.AutomatedMaster object at 0x000002202E854348>>
Traceback (most recent call last):
  File "C:\Users\smalviya\Desktop\infection_monkey\monkey\infection_monkey\master\automated_master.py", line 234, in _run_plugins
    callback(p)
  File "C:\Users\smalviya\Desktop\infection_monkey\monkey\infection_monkey\master\automated_master.py", line 201, in _run_pba
    for pba_data in self._puppet.run_pba(pba.name, pba.options):
  File "C:\Users\smalviya\Desktop\infection_monkey\monkey\infection_monkey\puppet\puppet.py", line 41, in run_pba
    return pba.run(options)
  File "C:\Users\smalviya\Desktop\infection_monkey\monkey\infection_monkey\post_breach\custom_pba\custom_pba.py", line 37, in run
    return super().run(options)
  File "C:\Users\smalviya\Desktop\infection_monkey\monkey\infection_monkey\post_breach\pba.py", line 46, in run
    result = exec_funct()
  File "C:\Users\smalviya\Desktop\infection_monkey\monkey\infection_monkey\post_breach\custom_pba\custom_pba.py", line 66, in _execute_default
    return super(CustomPBA, self)._execute_default()
  File "C:\Users\smalviya\Desktop\infection_monkey\monkey\infection_monkey\post_breach\pba.py", line 83, in _execute_default
    self.command, stderr=subprocess.STDOUT, shell=True, timeout=self.timeout
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 59: invalid start byte
```

## To Reproduce
1. Try running a custom PBA on Windows

## Expected behavior
It should run with no errors.

## Machine version (please complete the following information):
 - OS: Windows

**Comment by cakekoa** [comment]
PBAs are being removed in #2442
