### ISSUE TITLE
Relay connection timeouts

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#2596]
## Describe the bug
One of the agents didn't send its shutdown signal. 

The agent was running in tunneling - 10:
[broken_infection-monkey-agent-2022-11-16-10-27-24-up7xxgno.log](https://github.com/guardicore/monkey/files/10023399/broken_infection-monkey-agent-2022-11-16-10-27-24-up7xxgno.log)

It was started and using relay from tunneling - 9:

[caller_infection-monkey-agent-2022-11-16-10-27-11-4xsomy1p.log](https://github.com/guardicore/monkey/files/10023420/caller_infection-monkey-agent-2022-11-16-10-27-11-4xsomy1p.log)

Island logs:
[monkey_island.log](https://github.com/guardicore/monkey/files/10023429/monkey_island.log)

## To Reproduce
1. Happened in tunneling, so that I guess?
2. I've added networks to segmentation tests, so maybe those tests are also playing a part here

Overall this is a hard to get error

## More info

I think this error happened in `monkey/infection_monkey/island_api_client/http_island_api_client.py` `get_agent_sygnals` method, when island didn't respond in 2.5 seconds to whether agent kill signal was present. I've lowered the timeout in an attempt to more reliably reproduce this, here's the log:
[infection-monkey-agent-2022-11-16-15-43-23-ni03il41.log](https://github.com/guardicore/monkey/files/10023625/infection-monkey-agent-2022-11-16-15-43-23-ni03il41.log)

## Bug manifestation

Typical error looks like
```
2022-11-18 11:50:10,419 [9868:MainThread:ERROR] monkey.cleanup.400: An error occurred while cleaning up the monkey agent: HTTPSConnectionPool(host='10.2.1.9', port=8080): Read timed out. (read timeout=0.5)
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 382, in _make_request
  File "urllib3/connectionpool.py", line 1010, in _validate_conn
  File "urllib3/connection.py", line 421, in connect
  File "urllib3/util/ssl_.py", line 453, in ssl_wrap_socket
  File "urllib3/util/ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
socket.timeout: _ssl.c:1074: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 499, in send
  File "urllib3/connectionpool.py", line 756, in urlopen
  File "urllib3/util/retry.py", line 532, in increment
  File "urllib3/packages/six.py", line 770, in reraise
  File "urllib3/connectionpool.py", line 706, in urlopen
  File "urllib3/connectionpool.py", line 385, in _make_request
  File "urllib3/connectionpool.py", line 337, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='10.2.1.9', port=8080): Read timed out. (read timeout=0.5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "infection_monkey/island_api_client/http_island_api_client.py", line 34, in decorated
  File "infection_monkey/island_api_client/http_island_api_client.py", line 58, in wrapper
  File "infection_monkey/island_api_client/http_island_api_client.py", line 169, in get_agent_signals
  File "infection_monkey/island_api_client/http_island_api_client.py", line 94, in _get
  File "requests/api.py", line 73, in get
  File "requests/api.py", line 59, in request
  File "requests/sessions.py", line 587, in request
  File "requests/sessions.py", line 701, in send
  File "requests/adapters.py", line 578, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='10.2.1.9', port=8080): Read timed out. (read timeout=0.5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "infection_monkey/master/control_channel.py", line 21, in wrapper
  File "infection_monkey/master/control_channel.py", line 39, in should_agent_stop
  File "infection_monkey/island_api_client/http_island_api_client.py", line 49, in decorated
infection_monkey.island_api_client.island_api_client_errors.IslandAPIError: HTTPSConnectionPool(host='10.2.1.9', port=8080): Read timed out. (read timeout=0.5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "infection_monkey/monkey.py", line 386, in cleanup
  File "infection_monkey/monkey.py", line 417, in _stop_relay
  File "infection_monkey/master/control_channel.py", line 23, in wrapper
infection_monkey.i_control_channel.IslandCommunicationError: HTTPSConnectionPool(host='10.2.1.9', port=8080): Read timed out. (read timeout=0.5)
2022-11-18 11:50:10,420 [9868:MainThread:INFO] monkey._self_delete.441: Cleaning up the Agent's artifacts
2022-11-18 11:50:10,420 [9868:MainThread:INFO] monkey._self_delete.453: Deleteing the Agent binary
```

Branch for WIP: 
https://github.com/guardicore/monkey/tree/fix-cleanup-bugs

**Comment by VakarisZ** [comment]
https://github.com/gevent/gevent/issues/1671

**Comment by VakarisZ** [comment]
More tests:
[test_relay.zip](https://github.com/guardicore/monkey/files/10042860/test_relay.zip)

**Comment by VakarisZ** [comment]
Crux of the issue:
Only one instance of `infection_monkey.network.relay.relay_connection_handler.RelayConnectionHandler.handle_new_connection` can be running at a time, so if the `sock.recv` freezes, other connections have  to wait:

![image](https://user-images.githubusercontent.com/36815064/202749777-807fd07f-af0c-4045-8884-ce88d93d2426.png)

```
2022-11-18 11:50:09,051 [9959:TCPConnectionHandler:DEBUG] tcp_connection_handler.run.44: New connection received from: ('10.2.2.3', 52335)
2022-11-18 11:50:09,052 [9959:TCPConnectionHandler:DEBUG] relay_connection_handler.handle_new_connection.26: Getting remote port
2022-11-18 11:50:09,052 [9959:TCPConnectionHandler:DEBUG] relay_connection_handler.handle_new_connection.29: Remote port acquired
2022-11-18 11:50:10,012 [9959:MainThread:DEBUG] http_island_api_client._get.92: GET https://10.2.2.249:5000/api/agent-signals/96b60f0a-b1e9-4ee8-a34c-4853a89937c7, timeout=0.5
2022-11-18 11:50:12,051 [9959:TCPConnectionHandler:DEBUG] relay_connection_handler.handle_new_connection.34: Relay control message received
```

**Comment by mssalvatore** [comment]
I think the best way to fix this is to use keep-alive connections. This will significantly reduce the total number of connections a relay will need to handle. Pipes will be longer lived and latency will be significantly decreased. I think `sock.recv()` takes a long time to handle large messages, which won't be an issue anymore if we use keep-alive connections.

As an added bonus, it would resolve a potential race condition that @cakekoa and I have been theorizing about.

We'll have to do some more investegation to see if it's a viable solution.

**Comment by VakarisZ** [comment]
Mostly mitigated with retries and `keep-alive` connection in #2603, but theoretically can still happen if many connections are initiated at once

**Comment by mssalvatore** [comment]
Since this issue has been mitigated with keep-alive connections and retries, it is presently a theoretical concern, but not a practical concern.

I'm closing this for now. If this issue pops up in the real world, we can revisit it.
