### ISSUE TITLE
utf8 or gbk bug

### ISSUE THREAD

**Issue by moyuwa** [guardicore/monkey#3095]
windows server 2008 r2 ，Agent startup error

```
[4512:MainThread:ERROR] main._run_agent.155: Exception t
hrown from monkey's start function. More info: 'utf-8' codec can't decode byte 0
xb9 in position 2: invalid start byte
Traceback (most recent call last):
  File "infection_monkey\main.py", line 153, in _run_agent
  File "infection_monkey\monkey.py", line 238, in start
  File "infection_monkey\monkey.py", line 277, in _setup
  File "infection_monkey\network\firewall.py", line 60, in is_enabled
    for line in out.decode().splitlines():
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 2: invalid
start byte
```

```
[4512:MainThread:ERROR] monkey.cleanup.464: An error occ
urred while cleaning up the monkey agent: 'utf-8' codec can't decode byte 0xb9 i
n position 2: invalid start byte
Traceback (most recent call last):
  File "infection_monkey\monkey.py", line 446, in cleanup
  File "infection_monkey\network\firewall.py", line 60, in is_enabled
    for line in out.decode().splitlines():
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 2: invalid
start byte
```

**Comment by mssalvatore** [comment]
Hi, @moyuwa . Infection Monkey dose not support Windows 2008, as [support from Microsoft ended in 2020](https://learn.microsoft.com/en-us/windows-server/get-started/extended-security-updates-overview). Please see [this page](https://techdocs.akamai.com/infection-monkey/docs/operating-systems) for a list of supported operating systems.
