### ISSUE TITLE
Support different windows system languages

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#3432]
**Is your feature request related to a problem? Please describe.**
If the system language on windows is **not English** some CMD commands will fail. This happens due to the agent parsing the command line output as if it was English. Various other bugs will happen when trying to read non-english text, for example (monkey v2.2.0, French system language): 
```
2023-06-16 16:21:08,127 [7516:MainThread:ERROR] main._run_agent.174: Exception thrown from monkey's start function. More info: 'utf-8' codec can't decode byte 0x8a in position 7: invalid start byte
Traceback (most recent call last):
  File "infection_monkey\main.py", line 172, in _run_agent
  File "infection_monkey\monkey.py", line 295, in start
  File "infection_monkey\monkey.py", line 334, in _setup
  File "infection_monkey\network\firewall.py", line 60, in is_enabled
    for line in out.decode().splitlines():
                ^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 7: invalid start byte
2023-06-16 16:21:08,128 [7516:MainThread:INFO] monkey.cleanup.503: Agent cleanup started
2023-06-16 16:21:08,223 [7516:MainThread:ERROR] monkey.cleanup.534: An error occurred while cleaning up the monkey agent: 'utf-8' codec can't decode byte 0x8a in position 7: invalid start byte
Traceback (most recent call last):
  File "infection_monkey\monkey.py", line 512, in cleanup
  File "infection_monkey\network\firewall.py", line 60, in is_enabled
    for line in out.decode().splitlines():
                ^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 7: invalid start byte
```

**Describe the solution you'd like**

Use more robust decoders and parse response values by position to support more different system languages for windows

**Describe alternatives you've considered**
 - Agent checking system language to see if it's supported
 - Keeping as is, just an entry in the readme that we don't support other system languages

**Comment by Bratox** [comment]
Here is a solution to solve this issue when you don't want to change your system language
Go to **Settings** and **Time & Language**
![image](https://github.com/guardicore/monkey/assets/51783087/8352f747-5ddd-4ec4-bc76-ed0c61a51a91)
**Language**
![image](https://github.com/guardicore/monkey/assets/51783087/8510f2fc-f833-45a3-871e-1dc1f3f26e6f)
**Administrative language settings**
![image](https://github.com/guardicore/monkey/assets/51783087/89a2aeb6-541b-42db-b795-9641956aea50)
Click on **Change system locale**
![image](https://github.com/guardicore/monkey/assets/51783087/b1103067-3af8-42e3-b843-571e12833cad)
And check **Beta : Use Unicode UTF-8...**
![image](https://github.com/guardicore/monkey/assets/51783087/5deb23e4-e453-44b3-8eea-590fbe467360)
This should help you to make Infection Monkey work in your non English System
