### ISSUE TITLE
Re-register "old" monkeys which are still alive

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#347]
## Expected Behavior
When we get a request from a Monkey we don't recognize (i.e. the Monkey can't be found in mongo) in functions like sending Log, we should ask it who it is and reregister it in the DB as a new monkey. 

## Actual Behavior
```
2019-06-06 15:00:41,754 - telemetry.py:62 -       post() - ERROR - Exception caught while processing telemetry
Traceback (most recent call last):
  File "/var/monkey/monkey_island/cc/resources/telemetry.py", line 55, in post
    NodeService.update_monkey_modify_time(monkey["_id"])
TypeError: 'NoneType' object has no attribute '__getitem__'
2019-06-06 15:00:41,765 - wsgi.py:374 -       _log() - INFO - 200 POST /api/telemetry (23.101.28.144) 19.51ms
2019-06-06 15:00:41,797 - app.py:1780 - log_exception() - ERROR - Exception on /api/log [POST]
Traceback (most recent call last):
  File "/var/monkey/monkey_island/bin/python/local/lib/python2.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/monkey/monkey_island/bin/python/local/lib/python2.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/monkey/monkey_island/bin/python/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/var/monkey/monkey_island/bin/python/local/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/monkey/monkey_island/bin/python/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/var/monkey/monkey_island/cc/resources/log.py", line 29, in post
    monkey_id = NodeService.get_monkey_by_guid(telemetry_json['monkey_guid'])['_id']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

## Steps to Reproduce the Problem

Haven't actually tried this, but it happened to a user

  1. Run monkey + island
  2. Delete monkey from DB while monkey is alive

**Comment by mssalvatore** [comment]
Can we have any confidence that this monkey is legit? What if it's a _malicious monkey_ that wants to fill our report with garbage data to obfuscate results?

**Comment by VakarisZ** [comment]
We don't authenticate monkeys anyways, I think it's due to complexities of SSL channel. Someone clogging up report is least of my concerns.

**Comment by mssalvatore** [comment]
If the monkey is to be taken seriously as a Zero Trust assessment tool, it needs to adhere to Zero Trust principles. If we expect users to run this in their environments, they'll expect the monkeys to be authenticated.

**Comment by mssalvatore** [comment]
As part of the agent refactor project, monkeys will be much more reliably killed. Additionally, old monkeys which connect to a new simulation will be told to terminate themselves.
