### ISSUE TITLE
Can't use passwordless login

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#972]
## Describe the bug
```
2021-02-18 09:00:41,733 - app.py:1892 - log_exception() - ERROR - Exception on /api/auth [POST]
Traceback (most recent call last):
  File "C:\Users\Vakaris\test_venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Vakaris\test_venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Vakaris\test_venv\lib\site-packages\flask_restful\__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\Vakaris\test_venv\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\Vakaris\test_venv\lib\site-packages\flask_restful\__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\Vakaris\Desktop\infection_monkey\monkey\monkey_island\cc\resources\auth\auth.py", line 50, in post
    identity=user_store.UserStore.username_table[username].id)
  File "C:\Users\Vakaris\test_venv\lib\site-packages\flask_jwt_extended\utils.py", line 173, in create_access_token
    headers=headers)
  File "C:\Users\Vakaris\test_venv\lib\site-packages\flask_jwt_extended\jwt_manager.py", line 522, in _create_access_token
    headers=headers
  File "C:\Users\Vakaris\test_venv\lib\site-packages\flask_jwt_extended\tokens.py", line 77, in encode_access_token
    json_encoder=json_encoder, headers=headers)
  File "C:\Users\Vakaris\test_venv\lib\site-packages\flask_jwt_extended\tokens.py", line 30, in _encode_jwt
    json_encoder=json_encoder, headers=headers).decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

## To Reproduce
1. pip install requirements according to island requirements
2. Choose passwordless login option when registering
3. See error

## Expected behavior
We should update requirements to use the latest `Flask-JWT-Extended`

**Comment by mssalvatore** [comment]
Duplicate of https://github.com/guardicore/monkey/issues/960

**Comment by VakarisZ** [comment]
Closing because of a duplicate
